// Extracted Lunar Mission Data and Translations
const lunarSites = [
    // APOLLO
    {type: 'mission', id: 'apollo11', name: 'Apollo 11', lat: 0.6740, lon: 23.4720, wikiTitle: 'Apollo_11', description: 'First human landing (1969). Neil Armstrong and Buzz Aldrin.', descriptionAm: 'የመጀመሪያው የሰው ልጅ ማረፊያ (1969)። ኒል አርምስትሮንግ እና በዝ አልድሪን።'},
    {type: 'mission', id: 'apollo12', name: 'Apollo 12', lat: -3.0123, lon: -23.4215, wikiTitle: 'Apollo_12', description: 'Pinpoint landing near Surveyor 3 (1969). Pete Conrad and Alan Bean.', descriptionAm: 'ከሰርቬየር 3 አቅራቢያ ትክክለኛ ማረፊያ (1969)። ፒት ኮንራድ እና አላን ቢን።'},
    {type: 'mission', id: 'apollo14', name: 'Apollo 14', lat: -3.6453, lon: -17.4713, wikiTitle: 'Apollo_14', description: 'Fra Mauro highlands landing (1971). Alan Shepard and Edgar Mitchell.', descriptionAm: 'የፍራ ማውሮ ከፍተኛ ቦታዎች ማረፊያ (1971)። አላን ሸፓርድ እና ኤድጋር ሚቼል።'},
    {type: 'mission', id: 'apollo15', name: 'Apollo 15', lat: 26.1322, lon: 3.6338, wikiTitle: 'Apollo_15', description: 'First J-mission with Lunar Roving Vehicle at Hadley Rille (1971).', descriptionAm: 'የመጀመሪያው ጄ-ተልዕኮ ከጨረቃ አውቶሞቢል ጋር (1971)።'},
    {type: 'mission', id: 'apollo16', name: 'Apollo 16', lat: -8.9730, lon: 15.5001, wikiTitle: 'Apollo_16', description: 'Descartes Highlands landing (1972). John Young and Charles Duke.', descriptionAm: 'የዴስካርትስ ከፍተኛ ቦታዎች ማረፊያ (1972)። ጆን ያንግ እና ቻርለስ ዱክ።'},
    {type: 'mission', id: 'apollo17', name: 'Apollo 17', lat: 20.1908, lon: 30.7716, wikiTitle: 'Apollo_17', description: 'Taurus-Littrow valley. Final Apollo mission (1972). Eugene Cernan and Harrison Schmitt.', descriptionAm: 'ታውረስ-ሊትሮው ቆሬ። የመጨረሻው የአፖሎ ተልዕኮ (1972)። ዩጂን ሰርናን እና ሃሪሰን ሽሚት።'},

    // LUNA
    {type: 'mission', id: 'luna-2', name: 'Luna 2', lat: 29.1, lon: 0.0, wikiTitle: 'Luna_2', description: 'First human-made object to reach the Moon (1959). Intentional hard impact.', descriptionAm: 'ጨረቃ ላይ የደረሰ የመጀመሪያው ሰው ሰራሽ አካል (1959)።'},
    {type: 'mission', id: 'luna-9', name: 'Luna 9', lat: 7.08, lon: -64.37, wikiTitle: 'Luna_9', description: 'First spacecraft to achieve a soft landing on the Moon (1966).', descriptionAm: 'በጨረቃ ላይ ለስላሳ ማረፊያ ያደረገ የመጀመሪያው መንኮራኩር (1966)።'},
    {type: 'mission', id: 'luna-13', name: 'Luna 13', lat: 18.87, lon: -62.05, wikiTitle: 'Luna_13', description: 'Soviet lander (1966) equipped with a soil penetrometer.', descriptionAm: 'የሶቪየት ማረፊያ መንኮራኩር (1966)።'},
    {type: 'mission', id: 'luna-16', name: 'Luna 16', lat: -0.68, lon: 56.30, wikiTitle: 'Luna_16', description: 'First successful robotic sample return mission (1970).', descriptionAm: 'የመጀመሪያው የተሳካ የናሙና መመለሻ ተልዕኮ (1970)።'},
    {type: 'mission', id: 'luna-17', name: 'Luna 17 (Lunokhod 1)', lat: 38.28, lon: -35.0, wikiTitle: 'Lunokhod_1', description: 'Delivered Lunokhod 1, the first successful robotic lunar rover (1970).', descriptionAm: 'የመጀመሪያውን የጨረቃ ሮቨር (ሉኖኮድ 1) ያደረሰ (1970)።'},
    {type: 'mission', id: 'luna-20', name: 'Luna 20', lat: 3.53, lon: 56.55, wikiTitle: 'Luna_20', description: 'Robotic sample return mission from the Apollonius highlands (1972).', descriptionAm: 'ሮቦቲክ የናሙና መመለሻ ተልዕኮ (1972)።'},
    {type: 'mission', id: 'luna-21', name: 'Luna 21 (Lunokhod 2)', lat: 25.85, lon: 30.45, wikiTitle: 'Lunokhod_2', description: 'Delivered Lunokhod 2 rover, which traveled 39 km across the surface (1973).', descriptionAm: 'ሉኖኮድ 2 ሮቨርን ያደረሰ (1973)።'},
    {type: 'mission', id: 'luna-24', name: 'Luna 24', lat: 12.71, lon: 62.22, wikiTitle: 'Luna_24', description: 'The third and final successful Soviet robotic sample return mission (1976).', descriptionAm: 'የመጨረሻው የሶቪየት ሮቦቲክ የናሙና መመለሻ ተልዕኮ (1976)።'},

    // SURVEYOR
    {type: 'mission', id: 'surveyor-1', name: 'Surveyor 1', lat: -2.47, lon: -43.34, wikiTitle: 'Surveyor_1', description: 'First US spacecraft to achieve a soft landing on the Moon (1966).', descriptionAm: 'በጨረቃ ላይ ለስላሳ ማረፊያ ያደረገ የመጀመሪያው የአሜሪካ መንኮራኩር (1966)።'},
    {type: 'mission', id: 'surveyor-3', name: 'Surveyor 3', lat: -3.01, lon: -23.34, wikiTitle: 'Surveyor_3', description: 'Landed in 1967. Parts were later retrieved by Apollo 12 astronauts.', descriptionAm: 'በ1967 አረፈ። ክፍሎቹ በኋላ በአፖሎ 12 ጠፈርተኞች ተወስደዋል።'},
    {type: 'mission', id: 'surveyor-5', name: 'Surveyor 5', lat: 1.41, lon: 23.18, wikiTitle: 'Surveyor_5', description: 'Landed in 1967. Conducted the first alpha particle x-ray spectrometry on the Moon.', descriptionAm: 'በ1967 አረፈ። የመጀመሪያውን የአልፋ ቅንጣት ራጅ ስፔክትሮሜትሪ አከናወነ።'},
    {type: 'mission', id: 'surveyor-6', name: 'Surveyor 6', lat: 0.46, lon: -1.37, wikiTitle: 'Surveyor_6', description: 'Landed in 1967. Was the first spacecraft to lift off from the lunar surface.', descriptionAm: 'በ1967 አረፈ። ከጨረቃ ገጽ ላይ የተነሳ የመጀመሪያው መንኮራኩር።'},
    {type: 'mission', id: 'surveyor-7', name: 'Surveyor 7', lat: -40.86, lon: -11.47, wikiTitle: 'Surveyor_7', description: 'Landed in 1968 near Tycho crater. The final Surveyor mission.', descriptionAm: 'የመጨረሻው የሰርቬየር ተልዕኮ በታይኮ ቆሬ አቅራቢያ አረፈ (1968)።'},

    // CHANG'E
    {type: 'mission', id: 'change-3', name: 'Chang\'e 3 (Yutu)', lat: 44.12, lon: -19.51, wikiTitle: 'Chang\'e_3', description: 'Chinese lander and Yutu rover. First soft landing since 1976 (2013).', descriptionAm: 'የቻይና ማረፊያ መንኮራኩር እና ዩቱ ሮቨር። ከ1976 ወዲህ የመጀመሪያው ለስላሳ ማረፊያ (2013)።'},
    {type: 'mission', id: 'change-4', name: 'Chang\'e 4 (Yutu-2)', lat: -45.45, lon: 177.59, wikiTitle: 'Chang\'e_4', description: 'First mission to land on the far side of the Moon (2019).', descriptionAm: 'በጨረቃ ሩቅ ጎን ያረፈ የመጀመሪያው ተልዕኮ (2019)።'},
    {type: 'mission', id: 'change-5', name: 'Chang\'e 5', lat: 43.06, lon: -51.91, wikiTitle: 'Chang\'e_5', description: 'Chinese sample return mission from Oceanus Procellarum (2020).', descriptionAm: 'የቻይና የናሙና መመለሻ ተልዕኮ (2020)።'},
    {type: 'mission', id: 'change-6', name: 'Chang\'e 6', lat: -41.6, lon: 153.98, wikiTitle: 'Chang\'e_6', description: 'First mission to return samples from the lunar far side (2024).', descriptionAm: 'ከጨረቃ ሩቅ ጎን ናሙናዎችን የመለሰ የመጀመሪያው ተልዕኮ (2024)።'},

    // OTHER MODERN LANDERS
    {type: 'mission', id: 'chandrayaan-3', name: 'Chandrayaan-3 (Vikram/Pragyan)', lat: -69.37, lon: 32.32, wikiTitle: 'Chandrayaan-3', description: 'ISRO lander and rover. First to land near the lunar south pole (2023).', descriptionAm: 'የህንድ ማረፊያ መንኮራኩር። በጨረቃ ደቡብ ዋልታ አቅራቢያ በማረፍ የመጀመሪያው ነው (2023)።'},
    {type: 'mission', id: 'slim', name: 'SLIM (JAXA)', lat: -13.31, lon: 25.25, wikiTitle: 'Smart_Lander_for_Investigating_Moon', description: 'Smart Lander for Investigating Moon (JAXA). Achieved an unprecedented pinpoint landing (2024).', descriptionAm: 'የጃፓን መንኮራኩር። ታይቶ የማይታወቅ ትክክለኛ ማረፊያ አከናወነ (2024)።'},
    {type: 'mission', id: 'odysseus', name: 'IM-1 Odysseus', lat: -80.12, lon: 1.44, wikiTitle: 'IM-1', description: 'First successful commercial lunar lander (Intuitive Machines, 2024).', descriptionAm: 'የመጀመሪያው የተሳካ የንግድ ጨረቃ ማረፊያ መንኮራኩር (2024)።'},

    // CRATERS
    {type: 'crater', id: 'tycho', name: 'Tycho Crater', lat: -43.30, lon: -11.20, wikiTitle: 'Tycho_(lunar_crater)', description: 'A very prominent crater with a spectacular ray system, estimated at 108 million years old.', descriptionAm: 'እጅግ በጣም ታዋቂ የሆነ ቆሬ፣ 108 ሚሊዮን ዓመታት ዕድሜ እንዳለው ይገመታል።'},
    {type: 'crater', id: 'copernicus', name: 'Copernicus Crater', lat: 9.62, lon: -20.08, wikiTitle: 'Copernicus_(lunar_crater)', description: 'A magnificent impact crater visible with binoculars, located in eastern Oceanus Procellarum.', descriptionAm: 'በምስራቃዊ ኦሽኑስ ፕሮሴላረም ውስጥ የሚገኝ አስደናቂ ቆሬ።'},
    {type: 'crater', id: 'aristarchus', name: 'Aristarchus Crater', lat: 23.7, lon: -47.4, wikiTitle: 'Aristarchus_(crater)', description: 'Considered the brightest of the large formations on the lunar surface.', descriptionAm: 'በጨረቃ ገጽ ላይ ካሉት ትላልቅ ቅርጾች በጣም ደማቅ እንደሆነ ይቆጠራል።'},
    {type: 'crater', id: 'clavius', name: 'Clavius Crater', lat: -58.4, lon: -14.4, wikiTitle: 'Clavius_(crater)', description: 'One of the largest crater formations on the Moon and the second largest crater on the visible near side.', descriptionAm: 'በጨረቃ ላይ ካሉት ትላልቅ የቆሬ ቅርጾች አንዱ።'},
    {type: 'crater', id: 'aristoteles', name: 'Aristoteles Crater', lat: 50.2, lon: 17.4, wikiTitle: 'Aristoteles_(crater)', description: 'A large lunar impact crater that lies near the southern edge of the Mare Frigoris.', descriptionAm: 'በማሬ ፍሪጎሪስ ደቡባዊ ጫፍ አቅራቢያ የሚገኝ ትልቅ የጨረቃ ቆሬ።'},
    {type: 'crater', id: 'eratosthenes', name: 'Eratosthenes Crater', lat: 14.5, lon: -11.3, wikiTitle: 'Eratosthenes_(crater)', description: 'A relatively deep, sharply defined lunar impact crater that lies between the Mare Imbrium and Sinus Aestuum.', descriptionAm: 'በማሬ ኢምብሪየም እና ሳይነስ ኤስቱየም መካከል የሚገኝ ጥልቅ ቆሬ።'},
    {type: 'crater', id: 'archimedes', name: 'Archimedes Crater', lat: 29.7, lon: -4.0, wikiTitle: 'Archimedes_(crater)', description: 'A large lunar impact crater on the eastern edges of the Mare Imbrium.', descriptionAm: 'በማሬ ኢምብሪየም ምስራቃዊ ጠርዝ ላይ የሚገኝ ትልቅ ቆሬ።'},
    {type: 'crater', id: 'gassendi', name: 'Gassendi Crater', lat: -17.5, lon: -39.9, wikiTitle: 'Gassendi_(crater)', description: 'A large lunar impact crater feature located at the northern edge of Mare Humorum.', descriptionAm: 'በማሬ ሁሞረም ሰሜናዊ ጫፍ ላይ የሚገኝ ትልቅ ቆሬ።'},
    {type: 'crater', id: 'schickard', name: 'Schickard Crater', lat: -44.4, lon: -55.1, wikiTitle: 'Schickard_(crater)', description: 'A lunar impact crater of the form called a walled plain, located in the southwest sector of the Moon.', descriptionAm: 'በጨረቃ ደቡብ ምዕራብ ክፍል የሚገኝ ትልቅ ሜዳማ ቆሬ።'},
    {type: 'crater', id: 'grimaldi', name: 'Grimaldi Crater', lat: -5.4, lon: -68.4, wikiTitle: 'Grimaldi_(crater)', description: 'A large, dark basin located near the western limb of the Moon.', descriptionAm: 'በጨረቃ ምዕራባዊ ጫፍ አቅራቢያ የሚገኝ ትልቅ እና ጥቁር ተፋሰስ።'},
    {type: 'crater', id: 'langrenus', name: 'Langrenus Crater', lat: -8.9, lon: 61.0, wikiTitle: 'Langrenus_(crater)', description: 'A prominent impact crater located near the eastern lunar limb, featuring a terraced inner wall.', descriptionAm: 'በምስራቃዊ የጨረቃ ጫፍ አቅራቢያ የሚገኝ ታዋቂ ቆሬ።'},
    {type: 'crater', id: 'theophilus', name: 'Theophilus Crater', lat: -11.4, lon: 26.4, wikiTitle: 'Theophilus_(crater)', description: 'A prominent, well-preserved lunar impact crater that lies between Sinus Asperitatis in the north and Mare Nectaris to the southeast.', descriptionAm: 'በሳይነስ አስፐሪታቲስ እና በማሬ ኔክታሪስ መካከል የሚገኝ በጥሩ ሁኔታ የተጠበቀ ቆሬ።'},
    {type: 'crater', id: 'plato', name: 'Plato Crater', lat: 51.6, lon: -9.3, wikiTitle: 'Plato_(crater)', description: 'A lava-filled lunar impact crater on the northern near side of the Moon.', descriptionAm: 'በጨረቃ ሰሜናዊ ቅርብ ጎን የሚገኝ እና በላቫ የተሞላ ቆሬ።'},
    {type: 'crater', id: 'kepler', name: 'Kepler Crater', lat: 8.0, lon: -38.0, wikiTitle: 'Kepler_(lunar_crater)', description: 'A lunar impact crater that lies between the Oceanus Procellarum to the west and Mare Insularum in the east.', descriptionAm: 'በምዕራብ ኦሽኑስ ፕሮሴላረም እና በምስራቅ ማሬ ኢንሱላረም መካከል የሚገኝ ቆሬ።'},
    {type: 'crater', id: 'ptolemaeus', name: 'Ptolemaeus Crater', lat: -9.2, lon: -1.8, wikiTitle: 'Ptolemaeus_(lunar_crater)', description: 'An ancient lunar impact crater close to the center of the near side.', descriptionAm: 'በቅርብ ጎኑ መሃል አቅራቢያ የሚገኝ ጥንታዊ ቆሬ።'},
    
    // MARIA
    {type: 'mare', id: 'mare-imbrium', name: 'Mare Imbrium (Sea of Showers)', lat: 32.8, lon: -15.6, wikiTitle: 'Mare_Imbrium', description: 'A vast lunar mare created when lava flooded the giant crater formed by a massive asteroid impact.', descriptionAm: 'በአስትሮይድ ተጽዕኖ የተፈጠረ ግዙፍ ቆሬ በላቫ ሲጥለቀለቅ የተፈጠረ ሰፊ የጨረቃ ባህር።'},
    {type: 'mare', id: 'oceanus-procellarum', name: 'Oceanus Procellarum (Ocean of Storms)', lat: 10.4, lon: -53.4, wikiTitle: 'Oceanus_Procellarum', description: 'The largest of the lunar maria, stretching 2,500 kilometers across its north-south axis.', descriptionAm: '2,500 ኪሎ ሜትር የሚረዝም ትልቁ የጨረቃ ማሪያ።'},
    {type: 'mare', id: 'mare-serenitatis', name: 'Mare Serenitatis (Sea of Serenity)', lat: 28.0, lon: 17.5, wikiTitle: 'Mare_Serenitatis', description: 'A lunar mare located to the east of Mare Imbrium.', descriptionAm: 'ከማሬ ኢምብሪየም በስተምስራቅ የሚገኝ የጨረቃ ባህር።'},
    {type: 'mare', id: 'mare-crisium', name: 'Mare Crisium (Sea of Crises)', lat: 17.0, lon: 59.1, wikiTitle: 'Mare_Crisium', description: 'A lunar mare located in the Moon\'s Crisium basin, just northeast of Mare Tranquillitatis.', descriptionAm: 'ከማሬ ትራንኩሊቲ በስተሰሜን ምስራቅ በክሪሲየም ተፋሰስ ውስጥ የሚገኝ ባህር።'},
    {type: 'mare', id: 'mare-tranquillitatis', name: 'Mare Tranquillitatis (Sea of Tranquility)', lat: 8.5, lon: 31.4, wikiTitle: 'Mare_Tranquillitatis', description: 'A lunar mare that served as the landing site for Apollo 11.', descriptionAm: 'ለአፖሎ 11 ማረፊያ ቦታ ሆኖ ያገለገለ የጨረቃ ባህር።'},
    {type: 'mare', id: 'mare-nectaris', name: 'Mare Nectaris (Sea of Nectar)', lat: -15.2, lon: 34.6, wikiTitle: 'Mare_Nectaris', description: 'A small lunar mare located south of Mare Tranquillitatis.', descriptionAm: 'ከማሬ ትራንኩሊቲ በስተደቡብ የሚገኝ ትንሽ የጨረቃ ባህር።'},
    {type: 'mare', id: 'mare-fecunditatis', name: 'Mare Fecunditatis (Sea of Fecundity)', lat: -7.8, lon: 51.3, wikiTitle: 'Mare_Fecunditatis', description: 'A lunar mare in the eastern half of the visible Moon.', descriptionAm: 'በሚታየው የጨረቃ ምስራቃዊ አጋማሽ ላይ የሚገኝ የጨረቃ ባህር።'},
    {type: 'mare', id: 'mare-frigoris', name: 'Mare Frigoris (Sea of Cold)', lat: 56.0, lon: 1.4, wikiTitle: 'Mare_Frigoris', description: 'A lunar mare located in the far north of the Moon.', descriptionAm: 'በጨረቃ ሩቅ ሰሜን የሚገኝ የጨረቃ ባህር።'},
    
    // MOUNTAINS
    {type: 'mountain', id: 'mons-huygens', name: 'Mons Huygens', lat: 19.92, lon: -2.86, wikiTitle: 'Mons_Huygens', description: 'The Moon\'s tallest mountain, rising over 5.5 kilometers (18,000 ft) high.', descriptionAm: 'ከ5.5 ኪሎ ሜትር በላይ የሚረዝም የጨረቃ ረጅሙ ተራራ።'},
    {type: 'mountain', id: 'montes-alpes', name: 'Montes Alpes', lat: 46.4, lon: -0.8, wikiTitle: 'Montes_Alpes', description: 'A mountain range in the northern part of the Moon\'s near side, separated by the Vallis Alpes.', descriptionAm: 'በጨረቃ ሰሜናዊ ክፍል የሚገኝ የተራራ ሰንሰለት።'},
    {type: 'mountain', id: 'montes-caucasus', name: 'Montes Caucasus', lat: 38.4, lon: 10.0, wikiTitle: 'Montes_Caucasus', description: 'A rugged mountain range forming the northeastern boundary of Mare Imbrium.', descriptionAm: 'የማሬ ኢምብሪየምን ሰሜናዊ ምስራቅ ድንበር የሚፈጥር የተራራ ሰንሰለት።'},
    {type: 'mountain', id: 'montes-jura', name: 'Montes Jura', lat: 47.1, lon: -34.0, wikiTitle: 'Montes_Jura', description: 'A mountain range forming the semi-circular boundary of Sinus Iridum.', descriptionAm: 'የሳይነስ ኢሪደምን ከፊል ክብ ድንበር የሚፈጥር የተራራ ሰንሰለት።'},
    {type: 'mountain', id: 'mons-pico', name: 'Mons Pico', lat: 45.7, lon: -8.9, wikiTitle: 'Mons_Pico', description: 'An isolated lunar mountain in the northern part of the Mare Imbrium basin.', descriptionAm: 'በማሬ ኢምብሪየም ተፋሰስ ሰሜናዊ ክፍል የሚገኝ ብቸኛ ተራራ።'},
    {type: 'mountain', id: 'mons-hadley', name: 'Mons Hadley', lat: 26.5, lon: 4.7, wikiTitle: 'Mons_Hadley', description: 'A massif in the northern portion of the Montes Apenninus range, near the Apollo 15 landing site.', descriptionAm: 'በአፖሎ 15 ማረፊያ ቦታ አቅራቢያ በሞንቴስ አፔኒነስ ሰንሰለት ሰሜናዊ ክፍል የሚገኝ ተራራ።'},
    {type: 'mountain', id: 'montes-apenninus', name: 'Montes Apenninus', lat: 19.0, lon: -4.0, wikiTitle: 'Montes_Apenninus', description: 'A rugged mountain range on the northern part of the Moon\'s near side, home to the Apollo 15 landing site.', descriptionAm: 'ለአፖሎ 15 ማረፊያ ቦታ መነሻ የሆነውና በሰሜናዊው ክፍል የሚገኝ የተራራ ሰንሰለት።'},
    
    // PLANNED
    {type: 'planned', id: 'artemis3-shackleton', name: 'Artemis III: Shackleton Crater', lat: -89.9, lon: 0.0, wikiTitle: 'Shackleton_(crater)', description: 'A planned candidate landing region for NASA\'s Artemis III mission, located exactly at the lunar South Pole. The crater interior is permanently shadowed, potentially trapping water ice.', descriptionAm: 'በጨረቃ ደቡብ ዋልታ ላይ የሚገኝ ለናሳ አርጤምስ 3 ተልዕኮ የታቀደ ማረፊያ ክልል።'},
    {type: 'planned', id: 'artemis3-malapert', name: 'Artemis III: Malapert Massif', lat: -85.99, lon: -2.94, wikiTitle: 'Malapert_(crater)', description: 'Another prime candidate landing region for Artemis III. This prominent mountain near the South Pole receives near-continuous sunlight and offers line-of-sight communication with Earth.', descriptionAm: 'ለአርጤምስ 3 ሌላ የታቀደ ማረፊያ ክልል። ከምድር ጋር ቀጥተኛ ግንኙነትን ይሰጣል።'}
];

const siteTranslations = {
    'Apollo 11': 'አፖሎ 11',
    'Apollo 12': 'አፖሎ 12',
    'Apollo 14': 'አፖሎ 14',
    'Apollo 15': 'አፖሎ 15',
    'Apollo 16': 'አፖሎ 16',
    'Apollo 17': 'አፖሎ 17',
    'Luna 2': 'ሉና 2',
    'Luna 9': 'ሉና 9',
    'Luna 13': 'ሉና 13',
    'Luna 16': 'ሉና 16',
    'Luna 17 (Lunokhod 1)': 'ሉና 17 (ሉኖኮድ 1)',
    'Luna 20': 'ሉና 20',
    'Luna 21 (Lunokhod 2)': 'ሉና 21 (ሉኖኮድ 2)',
    'Luna 24': 'ሉና 24',
    'Surveyor 1': 'ሰርቬየር 1',
    'Surveyor 3': 'ሰርቬየር 3',
    'Surveyor 5': 'ሰርቬየር 5',
    'Surveyor 6': 'ሰርቬየር 6',
    'Surveyor 7': 'ሰርቬየር 7',
    'Chang\'e 3 (Yutu)': 'ቻንግ 3 (Chang\'e 3)',
    'Chang\'e 4 (Yutu-2)': 'ቻንግ 4 (Chang\'e 4)',
    'Chang\'e 5': 'ቻንግ 5',
    'Chang\'e 6': 'ቻንግ 6',
    'Chandrayaan-3 (Vikram/Pragyan)': 'ቻንድራያን-3 (Chandrayaan-3)',
    'SLIM (JAXA)': 'ስሊም (SLIM JAXA)',
    'IM-1 Odysseus': 'ኦዲሴየስ (Odysseus IM-1)',
    'Tycho Crater': 'ታይኮ ቆሬ',
    'Copernicus Crater': 'ኮፐርኒከስ ቆሬ',
    'Aristarchus Crater': 'አሪስታርከስ ቆሬ',
    'Clavius Crater': 'ክላቪየስ ቆሬ',
    'Mare Imbrium (Sea of Showers)': 'ማሬ ኢምብሪየም (የዝናብ ባህር)',
    'Oceanus Procellarum (Ocean of Storms)': 'ኦሽኑስ ፕሮሴላረም (የአውሎ ነፋስ ውቅያኖስ)',
    'Mare Serenitatis (Sea of Serenity)': 'ማሬ ሴሬኒታቲስ (የሰላም ባህር)',
    'Mare Crisium (Sea of Crises)': 'ማሬ ክሪሲየም (የቀውስ ባህር)',
    'Mons Huygens': 'ሁይገንስ ተራራ',
    'Artemis III: Shackleton Crater': 'አርጤምስ 3: ሻክልተን ቆሬ',
    'Artemis III: Malapert Massif': 'አርጤምስ 3: ማላፐርት ተራራ',
    'Plato Crater': 'ፕላቶ ቆሬ',
    'Kepler Crater': 'ኬፕለር ቆሬ',
    'Ptolemaeus Crater': 'ቶለሚ ቆሬ',
    'Mare Tranquillitatis (Sea of Tranquility)': 'ማሬ ትራንኩሊቲ (የጸጥታ ባህር)',
    'Mare Nectaris (Sea of Nectar)': 'ማሬ ኔክታሪስ (የኔክታር ባህር)',
    'Mare Fecunditatis (Sea of Fecundity)': 'ማሬ ፌኩንዲቲ (የምርታማነት ባህር)',
    'Mare Frigoris (Sea of Cold)': 'ማሬ ፍሪጎሪስ (የብርድ ባህር)',
    'Montes Apenninus': 'አፔኒነስ ተራሮች',
    'Aristoteles Crater': 'አርስቶትል ቆሬ',
    'Eratosthenes Crater': 'ኤራቶስቴንስ ቆሬ',
    'Archimedes Crater': 'አርኪሜዲስ ቆሬ',
    'Gassendi Crater': 'ጋሴንዲ ቆሬ',
    'Schickard Crater': 'ሺካርድ ቆሬ',
    'Grimaldi Crater': 'ግሪማልዲ ቆሬ',
    'Langrenus Crater': 'ላንግረኑስ ቆሬ',
    'Theophilus Crater': 'ቲዮፊለስ ቆሬ',
    'Montes Alpes': 'አልፕስ ተራሮች',
    'Montes Caucasus': 'ካውካሰስ ተራሮች',
    'Montes Jura': 'ጁራ ተራሮች',
    'Mons Pico': 'ፒኮ ተራራ',
    'Mons Hadley': 'ሃድሊ ተራራ'
};
